Task2 UI question answerer with tabs (variant A)
sergey-berezin/441_2_rusanov pull request #2
Opened 2023-10-25 19:06 UTC by AntonioRusan

2023-10-27 08:49 UTC, sergey-berezin requested changes

2023-10-27 08:49 UTC, sergey-berezin commented on Lab2_UI_Text_Question_Answerer/BertViewModel/MainViewModel.cs
> +                RaisePropertyChanged("TabItems");
Здесь и во всех остальных местах вместо константы  с именем свойства лучше использовать nameof(TabItems) и т.п. Это позволить обнаружить опечатки во время компиляции.

2023-10-27 08:49 UTC, sergey-berezin commented on Lab2_UI_Text_Question_Answerer/BertViewModel/TabItemViewModel.cs
> +                var answer = await Task.Run(() => bertModel.AnswerQuestionAsync(text, question, token));
Зачем нужен Task.Run?

2023-10-28 12:22 UTC, AntonioRusan commented on Lab2_UI_Text_Question_Answerer/BertViewModel/MainViewModel.cs
> +                RaisePropertyChanged("TabItems");
Исправил

2023-10-28 12:23 UTC, AntonioRusan commented on Lab2_UI_Text_Question_Answerer/BertViewModel/TabItemViewModel.cs
> +                var answer = await Task.Run(() => bertModel.AnswerQuestionAsync(text, question, token));
Поправил

2023-10-30 10:03 UTC, merged