Task3 Вариант 1a
sergey-berezin/441_2_rusanov pull request #3
Opened 2023-11-21 21:15 UTC by AntonioRusan

2023-11-26 13:34 UTC, sergey-berezin requested changes

2023-11-26 13:34 UTC, sergey-berezin commented on Lab3_DB_Text_Question_Answerer/DBModel/TextTab.cs
> +        public virtual ICollection<QuestionAndAnswer> QuestionAndAnswer { get; set; } = new ObservableCollection<QuestionAndAnswer>();
ObservableCollection применяется в основном в пользовательском интерфейсе. На уровне базы данных нужна действительно вся функциональность ObservableCollection или достаточно просто List<T>?

2023-11-26 20:47 UTC, AntonioRusan commented on Lab3_DB_Text_Question_Answerer/DBModel/TextTab.cs
> +        public virtual ICollection<QuestionAndAnswer> QuestionAndAnswer { get; set; } = new ObservableCollection<QuestionAndAnswer>();
Исправил

2023-11-27 09:45 UTC, sergey-berezin commented on Lab3_DB_Text_Question_Answerer/DBModel/TextTab.cs
> +        public virtual ICollection<QuestionAndAnswer> QuestionAndAnswer { get; set; } = new ObservableCollection<QuestionAndAnswer>();
Где загружаются связанные по QuestionAndAnswer сущности?

2023-11-27 09:46 UTC, sergey-berezin requested changes

2023-11-27 09:46 UTC, sergey-berezin commented on Lab3_DB_Text_Question_Answerer/BertViewModel/TabItemViewModel.cs
> +                var questionsFromDb = Database.QuestionsAndAnswers.Where(q => q.Question == question);
Нет проверки, что вопрос принадлежит тому же тексту.

2023-12-15 07:51 UTC, merged